# Generated by Django 2.1.7 on 2019-02-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pruebas',
            new_name='prueba',
        ),
    ]
